// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2026, 4:27:15 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/plugins/**/*.{js,ts,mjs}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/composables/**/*.{js,ts,mjs}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/utils/**/*.{js,ts,mjs}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/amirk/OneDrive/Desktop/UrbanTechStroy/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;